services:
  db:
    container_name: myworld_postgres_prod
    image: postgres:16.2
    environment:
      POSTGRES_DB: myworld
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped

  frontend:
    container_name: myworld-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile

    ports:
      - "443:443"

    networks:
      - db

  backend:
    container_name: myworld-backend
    build:
      context: ./backend
      dockerfile: Dockerfile

    depends_on:
      - db

    ports:
      - "8080:8080"

    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}

    networks:
      - db

networks:
  db:
    driver: bridge

volumes:
  db:
