server:
  port: 8080
  error:
    include-message: always

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"

aws:
  region: us-west-1
  s3:
    buckets:
      author: myworld-author

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
oidc:
  providers:
    google:
      client-id: ${GOOGLE_CLIENT_ID}
      client-secret: ${GOOGLE_CLIENT_SECRET}
      token-uri: https://oauth2.googleapis.com/token
      jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
      peoples-uri: https://people.googleapis.com/v1/people/me
    apple:
      client-id: x
      client-secret: x
      token-uri: x
      jwk-set-uri: x
      peoples-uri: x
    microsoft:
      client-id: ${MICROSOFT_CLIENT_ID}
      client-secret: ${MICROSOFT_CLIENT_SECRET}
      tenant-id: ${MICROSOFT_TENANT_ID}
      token-uri: https://login.microsoftonline.com/consumers/oauth2/v2.0/token
      jwk-set-uri: https://login.microsoftonline.com/consumers/discovery/v2.0/keys
      profile-uri: https://graph.microsoft.com/beta/me/profile
      photo-uri: https://graph.microsoft.com/v1.0/me/photo/$value
spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/myworld
    username: myworld_admin
    password: myworld_admin_pw_123
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  main:
    web-application-type: servlet
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  codec:
    max-in-memory-size: 10MB
  security:

flyway:
  url: jdbc:postgresql://localhost:5332/myworld
  schemas: myworld
  user: "myworld_admin"
  password: "myworld_admin_pw_123"
