name: Develop into Main

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 9,15,21,3 * * *'  # 9am, 3pm, 9pm, 3am UTC corresponds to 2am, 8am, 2pm, 8pm PST

jobs:
  merge-develop-to-main:
    runs-on: ubuntu-latest
    steps:
      - name: Standard Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'  # You can use 'zulu' or other distributions if preferred
          java-version: '21'
      - name: Set Git config
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
      - name: Fetch develop branch
        run: git fetch origin develop:develop
      - name: Create .env file from secret
        working-directory: ./backend
        run: |
          echo "${{ secrets.SECRETS_CONFIG }}" > ./src/main/resources/environment/secrets.env
      - name: Build and Test (Develop)
        working-directory: ./backend
        run: |
          git checkout develop
          mvn clean test
      - name: Merge develop into main
        if: success() # Only run if previous steps (build and test) were successful
        run: |
          git fetch --unshallow
          git checkout main
          git pull
          git merge --no-ff origin/develop -m "Auto-merge develop into main"
          git push
